### ISSUE TITLE
Getting new (undefined) error

### ISSUE THREAD

**Issue by shibmaster** [qistoph/MMM-nstreinen#31]
Hi guys,
 sorry for I have not been able to get more details about it. I have updated the module and all dependencies, but I get the following error still:
LIZE - Payload: [object Object]
[2020-06-07 14:01:25.272] [LOG]    Error: Error: Resource not found
    at /home/pi/MagicMirror/modules/nstreinen/node_modules/ns-api/nsapi.js:69:19
    at finalCallback (/home/pi/MagicMirror/modules/nstreinen/node_modules/httpreq/lib/httpreq.js:98:7)
    at IncomingMessage.<anonymous> (/home/pi/MagicMirror/modules/nstreinen/node_modules/httpreq/lib/httpreq.js:376:9)
    at IncomingMessage.emit (events.js:205:15)
    at endReadableNT (_stream_readable.js:1154:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:9) {
  statusCode: 404
}
Can someone help point me in the right direction? Thank you:)

**Comment by maximoei** [comment]
Had the same problem, apparently NS has changed its API structure/subscriptions. I also had an 'active' API key, but still didn't work. Re-subscribed to it again, now everything is fine!

**Comment by shibmaster** [comment]
I can confirm that after cancelling athe active subscription and getting the NS APP one, it works like a charm again! Thanks!

**Comment by shibmaster** [comment]
(CLOSE ISSUE)
